name: ROS2 Bitcoin Publisher Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up ROS 2
      uses: ros2/setup-ros@v0.2.0
      with:
        ros-distro: "humble"

    - name: Set up Python environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt  # 必要なパッケージをインストール
        pip install requests  # `requests`パッケージをインストール

    - name: Run tests
      run: |
        source venv/bin/activate
        ros2 run homework bitcoin_publisher  # 実際にノードを実行


