name: ROS2 Bitcoin Publisher Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up ROS 2
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos -o ros2.repos
        vcs import src < ros2.repos
        sudo apt update
        sudo apt install -y python3-pip python3-rosdep python3-rosinstall-generator python3-vcstool build-essential
        sudo rosdep init
        rosdep update

    - name: Install Python dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests

    - name: Build ROS 2 workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build

    - name: Run tests
      run: |
        source venv/bin/activate
        source install/setup.bash
        ros2 run homework bitcoin_publisher

